### ISSUE TITLE
GUI moves beyond screen bounds

### ISSUE THREAD

**Issue by reseune** [jfrouleau/PreciseEditor#3] opened 2019-04-02 00:08 UTC
As title... if the GUI (either the main one or the part specific one) is moved at all, repeated usage eventually moves it beyond the screen bounds. Exiting and reentering the VAB restores it.

**Comment by jfrouleau** [comment] 2019-04-12 10:45
I heard of this bug before but I never been able to reproduce it even if I'm using the mod a lot. If you can find a way please let me know.

**Comment by jfrouleau** [comment] 2019-04-20 15:42
Ahha ! Got it. I changed the **UI scale from 100% to 150%**, moved the window to the lower left corner, closed it and made it reappear beyond the screen bounds. I will work on this now.

**Comment by reseune** [comment] 2019-04-20 15:48
I'm so sorry! I missed your message asking for more info. Thank you for still looking into this despite my apparent absence.

**Comment by jfrouleau** [comment] 2019-05-02 02:19
I made a fix to take into account UI scaling which was a cause of the window going out of bounds. I don't know if it's the bug you got since it can't be reproduced easily so I'm gonna close this issue. If it come back and you find a way to reproduce it, feel free to open an issue again.

**Closed** 2019-05-02 02:19 UTC
